const NODE_RIGHT_CLICK = "NODE_RIGHT_CLICK";
const NODE_CHANGE_COMMENT = "NODE_CHANGE_COMMENT";
const NODE_ADD_CHILD = "NODE_ADD_CHILD";
const NODE_CHANGE_PARENT = "NODE_CHANGE_PARENT";
const TREE_REARRANGE = "TREE_REARRANGE";
const ADD_CONDITION_TASK = "ADD_CONDITION_TASK";
const DRAG_TAG_END = "DRAG_TAG_END";

export {
  NODE_RIGHT_CLICK,
  NODE_ADD_CHILD,
  NODE_CHANGE_PARENT,
  NODE_CHANGE_COMMENT,
  TREE_REARRANGE,
  ADD_CONDITION_TASK,
  DRAG_TAG_END
};