const NODE_RIGHT_CLICK = "NODE_RIGHT_CLICK";
const NODE_CHANGE_COMMENT = "NODE_CHANGE_COMMENT";
const NODE_ADD_CHILD = "NODE_ADD_CHILD";

export {
  NODE_RIGHT_CLICK,
  NODE_ADD_CHILD,
  NODE_CHANGE_COMMENT
};