const NODE_RIGHT_CLICK = "NODE_RIGHT_CLICK";
const NODE_CHANGE_COMMENT = "NODE_CHANGE_COMMENT";
const NODE_ADD_CHILD = "NODE_ADD_CHILD";
const TREE_REARRANGE = "TREE_REARRANGE";
const Add_CONDITION_TASK = "Add_CONDITION_TASK";

export {
  NODE_RIGHT_CLICK,
  NODE_ADD_CHILD,
  NODE_CHANGE_COMMENT,
  TREE_REARRANGE,
  Add_CONDITION_TASK
};