const ROOT_NODE_DEFAULT_SIZE = 30;
const PLAIN_NODE_DEFAULT_SIZE = 25;
const DEFAULT_EDGE_LENGTH = 25;
const DEFAULT_STROKE_WIDTH = 4;
const DEFAULT_THIN_STROKE_WIDTH = 2;

export {
  ROOT_NODE_DEFAULT_SIZE,
  PLAIN_NODE_DEFAULT_SIZE,
  DEFAULT_EDGE_LENGTH,
  DEFAULT_STROKE_WIDTH,
  DEFAULT_THIN_STROKE_WIDTH
};