const MILLSECONDS_PER_MINUTE = 60 * 1000;
const MILLSECONDS_PER_HOUR = MILLSECONDS_PER_MINUTE * 60;
const MILLSECONDS_PER_DAY = 24 * MILLSECONDS_PER_HOUR;

export {
  MILLSECONDS_PER_DAY,
  MILLSECONDS_PER_HOUR,
  MILLSECONDS_PER_MINUTE
};